name = input("Hi. What's your name? ")
age = input("And how old are you? ")
age = int(age)
weigh = input("Okay, last question. How many pounds do you weigh? ")
weigh = int(weigh)

print("\nDid you know that you're just", age/5, "in dog years?")
print("\nBut you're also over", age*365*24*60*60, "seconds old.")
print("\nIf a small child were trying to get your attention, your name would become:", name, name, name, name, name)
print("\nDid you know that on the moon you wold weigh only", weigh/6, "pounds?")
print("But on the sun, you'd weigh", weigh*109, "(but, ah... not for long).")
